[tox]
envlist = py312,py313,lint,mypy
minversion = 4.0

[testenv]
deps = .[dev]
commands = pytest {posargs}

[testenv:lint]
deps = .[dev]
commands = ruff check kronos/ tests/

[testenv:mypy]
deps = .[dev]
commands = mypy kronos/
