[tox]
envlist = py312,py313,lint,mypy,pyright
minversion = 4.0

[testenv]
deps = .[dev]
commands = pytest {posargs}

[testenv:lint]
deps = .[dev]
commands = ruff check kronos/ tests/

[testenv:mypy]
deps = .[dev]
commands = mypy kronos/

[testenv:pyright]
deps = .[dev]
commands = pyright kronos/ tests/

[testenv:docs]
deps = .[docs]
commands = sphinx-build -W -b html docs docs/_build/html

[testenv:genconfig]
deps = .
commands = oslo-config-generator --config-file etc/oslo-config-generator/kronos.conf
